// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pack_sizes.sql

package sqlc

import (
	"context"
)

const createPackSize = `-- name: CreatePackSize :exec
INSERT INTO pack_sizes (size)
VALUES ($1)
`

func (q *Queries) CreatePackSize(ctx context.Context, size int32) error {
	_, err := q.db.Exec(ctx, createPackSize, size)
	return err
}

const deletePackSize = `-- name: DeletePackSize :exec
DELETE FROM pack_sizes
WHERE size = $1
`

func (q *Queries) DeletePackSize(ctx context.Context, size int32) error {
	_, err := q.db.Exec(ctx, deletePackSize, size)
	return err
}

const deletePackSizes = `-- name: DeletePackSizes :exec
DELETE FROM pack_sizes
`

func (q *Queries) DeletePackSizes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deletePackSizes)
	return err
}

const listPackSizes = `-- name: ListPackSizes :many
SELECT size
FROM pack_sizes
ORDER BY size ASC
`

func (q *Queries) ListPackSizes(ctx context.Context) ([]int32, error) {
	rows, err := q.db.Query(ctx, listPackSizes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var size int32
		if err := rows.Scan(&size); err != nil {
			return nil, err
		}
		items = append(items, size)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
