// Code generated by MockGen. DO NOT EDIT.
// Source: ../../store/pack_sizes_store.go
//
// Generated by this command:
//
//	mockgen -source=../../store/pack_sizes_store.go -destination=./mocks.go -package=calculate
//

// Package calculate is a generated GoMock package.
package calculate

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPackSizesStore is a mock of PackSizesStore interface.
type MockPackSizesStore struct {
	ctrl     *gomock.Controller
	recorder *MockPackSizesStoreMockRecorder
	isgomock struct{}
}

// MockPackSizesStoreMockRecorder is the mock recorder for MockPackSizesStore.
type MockPackSizesStoreMockRecorder struct {
	mock *MockPackSizesStore
}

// NewMockPackSizesStore creates a new mock instance.
func NewMockPackSizesStore(ctrl *gomock.Controller) *MockPackSizesStore {
	mock := &MockPackSizesStore{ctrl: ctrl}
	mock.recorder = &MockPackSizesStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackSizesStore) EXPECT() *MockPackSizesStoreMockRecorder {
	return m.recorder
}

// DeletePackSize mocks base method.
func (m *MockPackSizesStore) DeletePackSize(ctx context.Context, size int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePackSize", ctx, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePackSize indicates an expected call of DeletePackSize.
func (mr *MockPackSizesStoreMockRecorder) DeletePackSize(ctx, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePackSize", reflect.TypeOf((*MockPackSizesStore)(nil).DeletePackSize), ctx, size)
}

// GetPackSizes mocks base method.
func (m *MockPackSizesStore) GetPackSizes(ctx context.Context) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPackSizes", ctx)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPackSizes indicates an expected call of GetPackSizes.
func (mr *MockPackSizesStoreMockRecorder) GetPackSizes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPackSizes", reflect.TypeOf((*MockPackSizesStore)(nil).GetPackSizes), ctx)
}

// ReplacePackSizes mocks base method.
func (m *MockPackSizesStore) ReplacePackSizes(ctx context.Context, sizes []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplacePackSizes", ctx, sizes)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplacePackSizes indicates an expected call of ReplacePackSizes.
func (mr *MockPackSizesStoreMockRecorder) ReplacePackSizes(ctx, sizes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplacePackSizes", reflect.TypeOf((*MockPackSizesStore)(nil).ReplacePackSizes), ctx, sizes)
}
